#!/usr/bin/env python

import sys, os

from urllib import urlopen
import csv
import json


#> catGetDatasetInfo v7-4-3

cmsswpath=os.environ.get('SRT_CMSSW_BASE_SCRAMRTDEL')+"/src/CATTools/CatAnalyzer/data/"
json_ = open(cmsswpath+"dataset.json")
dataset = json.load(json_)


args=["--jobName","--fileList","--maxFiles","--cfg","--transferDest","--args"]
for aa in dataset:
 if not (aa['name'].find("QCD")>-1 or aa['name'].find("SingleMuon")>-1 or aa['name'].find("SingleElectron")>-1) :
    
   ddd = "python create-batch "
   ddd+= args[0]+" "+aa['name']+" "
   ddd+= args[1]+" "+cmsswpath+"dataset_"+aa['name']+".txt "
   ddd+= args[2]+" 100 "
   #if ( aa['name'].find("Double")>-1 or aa['name'].find("MuonEG")>-1 ) :
   #  ddd+= args[3]+" run_ntupleMakerRD_cfg.py "
   #else :
   ddd+= args[3]+" run_ntupleMaker_cfg.py "
   ddd+= args[4]+" /store/user/youngjo/Cattools/v7-4-3/"+aa['name']

   eee="srmmkdir srm://cms-se.sdfarm.kr:8443/srm/v2/server?SFN=/xrootd/store/user/youngjo/Cattools/v7-4-3/"+aa['name']
   os.system(eee)
   print ddd
   os.system(ddd)

